### ISSUE TITLE
Trying to include chore commit to the changelog

### ISSUE THREAD

**Issue by jeremybdk** [mathieudutour/github-tag-action#50]
Hello,
I'm trying to include chore commit to the changelog but I cannot seem to get it working.
I've tried to add    `custom_release_rules: chore:patch` to the setup but without luck.

Any advices?

Thanks a lot,

**Comment by mathieudutour** [comment]
should be fixed on 5.1 now

**Comment by jeremybdk** [comment]
I'm sorry but chore are still not included in the changelog, should they be included by default or should I add a custom_release_rules for chore?

Thanks
