### ISSUE TITLE
Unable to bump major or minor version

### ISSUE THREAD

**Issue by stijnpiron** [mathieudutour/github-tag-action#7]
Hi,

How can I bump the major or minor version with your action?
The patch level is bumping as expected, but this is default behaviour, all attempts to bump major or minor versions are just resulting in a patch level bump...
I tried the examples from the readme (e.g.: `feat(deploy_scripts): update script`), but this does not work.

my script code is as follows:
```
# Generate build nummer on each push to every branch, this will be used to generate tags and releases when merged into master.
name: Update buildnumber

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag - new
        id: buildnumber
        uses: mathieudutour/github-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print new version number.
        env:
          version_number: ${{ steps.buildnumber.outputs.new_tag }}
        run: echo $version_number
```

Any idea what's going wrong here?
Thanks!

**Comment by tflander** [comment]
I'm having the same issue.  Not sure how to debug the analyzeCommits method brought in from @semantic-release/commit-analyzer.  Is there a secret handshake to configure commit rules?

**Comment by mathieudutour** [comment]
Hum I think it was because commit messages were often starting with a `\n`. Should be fixed now

**Comment by stijnpiron** [comment]
Hi,
Still no luck...
My commit message is copy-pasted from your documentation: 'feat(pencil): add 'graphiteWidth' option', but as you can see: the tag is not bumped as expected. I expected a v0.2.0, but I got a v0.1.10

Here some screenshots from my action scripts:
![version1](https://user-images.githubusercontent.com/2921903/74464504-ece7e180-4e93-11ea-8aee-98bfec00ed6c.png)
![version2](https://user-images.githubusercontent.com/2921903/74464506-ee190e80-4e93-11ea-9be3-d07731497b03.png)

Am I still doing something wrong, or..?

**Comment by mathieudutour** [comment]
hum seems to work for me. Could you try adding a secret to your repo: `ACTIONS_STEP_DEBUG` -> `true`? That should show more logs about what commit-analyzer is doing

**Comment by stijnpiron** [comment]
Here is some more logging:
```
2020-02-13T18:25:50.2345212Z commit 517e390db133f5904e2d275a1d77b287476edcef
2020-02-13T18:25:50.2345409Z Author: Stijn Piron <stijn.piron@gmail.com>
2020-02-13T18:25:50.2345600Z Date:   Thu Feb 13 19:25:26 2020 +0100
2020-02-13T18:25:50.2345726Z 
2020-02-13T18:25:50.2345916Z     feat(pencil): add <graphiteWidth> option
2020-02-13T18:25:50.2346881Z ::remove-matcher owner=checkout-git,::
2020-02-13T18:25:50.2348758Z Removed matchers: 'checkout-git'
2020-02-13T18:25:50.2366447Z ##[debug]Finishing: Run actions/checkout@master
2020-02-13T18:25:50.2374231Z ##[debug]Evaluating condition for step: 'Bump version and push tag'
2020-02-13T18:25:50.2375442Z ##[debug]Parsing expression: <success()>
2020-02-13T18:25:50.2377266Z ##[debug]Evaluating: success()
2020-02-13T18:25:50.2377644Z ##[debug]Evaluating success:
2020-02-13T18:25:50.2378367Z ##[debug]=> true
2020-02-13T18:25:50.2378822Z ##[debug]Result: true
2020-02-13T18:25:50.2379361Z ##[debug]Starting: Bump version and push tag
2020-02-13T18:25:50.2436580Z ##[debug]Loading inputs
2020-02-13T18:25:50.2474281Z ##[debug]Evaluating: secrets.GITHUB_TOKEN
2020-02-13T18:25:50.2474524Z ##[debug]Evaluating Index:
2020-02-13T18:25:50.2474716Z ##[debug]..Evaluating secrets:
2020-02-13T18:25:50.2474935Z ##[debug]..=> Object
2020-02-13T18:25:50.2475205Z ##[debug]..Evaluating String:
2020-02-13T18:25:50.2475435Z ##[debug]..=> 'GITHUB_TOKEN'
2020-02-13T18:25:50.2476126Z ##[debug]=> '***'
2020-02-13T18:25:50.2476389Z ##[debug]Result: '***'
2020-02-13T18:25:50.2479190Z ##[debug]Loading env
2020-02-13T18:25:50.2483070Z ##[group]Run mathieudutour/github-tag-action@v3
2020-02-13T18:25:50.2483220Z with:
2020-02-13T18:25:50.2483441Z   github_token: ***
2020-02-13T18:25:50.2483581Z   default_bump: patch
2020-02-13T18:25:50.2483716Z   tag_prefix: v
2020-02-13T18:25:50.2483854Z   release_branches: master
2020-02-13T18:25:50.2484001Z   create_annotated_tag: false
2020-02-13T18:25:50.2484140Z ##[endgroup]
2020-02-13T18:25:50.3900027Z [command]git fetch --tags
2020-02-13T18:25:51.0329913Z From https://github.com/stijnpiron/combaar
2020-02-13T18:25:51.0331502Z  * [new branch]      dependabot/changes -> origin/dependabot/changes
2020-02-13T18:25:51.0332186Z  * [new branch]      feature/refactor_project -> origin/feature/refactor_project
2020-02-13T18:25:51.0332908Z  * [new tag]         v0.0.2             -> v0.0.2
2020-02-13T18:25:51.0333767Z  * [new tag]         v0.0.3             -> v0.0.3
2020-02-13T18:25:51.0334319Z  * [new tag]         v0.1.0             -> v0.1.0
2020-02-13T18:25:51.0334884Z  * [new tag]         v0.1.1             -> v0.1.1
2020-02-13T18:25:51.0335440Z  * [new tag]         v0.1.10            -> v0.1.10
2020-02-13T18:25:51.0335994Z  * [new tag]         v0.1.11            -> v0.1.11
2020-02-13T18:25:51.0336559Z  * [new tag]         v0.1.2             -> v0.1.2
2020-02-13T18:25:51.0337101Z  * [new tag]         v0.1.3             -> v0.1.3
2020-02-13T18:25:51.0337749Z  * [new tag]         v0.1.4             -> v0.1.4
2020-02-13T18:25:51.0338251Z  * [new tag]         v0.1.5             -> v0.1.5
2020-02-13T18:25:51.0338748Z  * [new tag]         v0.1.6             -> v0.1.6
2020-02-13T18:25:51.0339245Z  * [new tag]         v0.1.7             -> v0.1.7
2020-02-13T18:25:51.0339746Z  * [new tag]         v0.1.8             -> v0.1.8
2020-02-13T18:25:51.0340245Z  * [new tag]         v0.1.9             -> v0.1.9
2020-02-13T18:25:51.0459823Z [command]git tag
2020-02-13T18:25:51.0498344Z v0.0.2
2020-02-13T18:25:51.0498869Z v0.0.3
2020-02-13T18:25:51.0499163Z v0.1.0
2020-02-13T18:25:51.0499456Z v0.1.1
2020-02-13T18:25:51.0499767Z v0.1.10
2020-02-13T18:25:51.0500044Z v0.1.11
2020-02-13T18:25:51.0500323Z v0.1.2
2020-02-13T18:25:51.0500596Z v0.1.3
2020-02-13T18:25:51.0500867Z v0.1.4
2020-02-13T18:25:51.0501139Z v0.1.5
2020-02-13T18:25:51.0501412Z v0.1.6
2020-02-13T18:25:51.0501682Z v0.1.7
2020-02-13T18:25:51.0501954Z v0.1.8
2020-02-13T18:25:51.0502227Z v0.1.9
2020-02-13T18:25:51.0533292Z [command]git rev-list --tags --topo-order --max-count=1
2020-02-13T18:25:51.0573094Z 6f8942e7b9a6be4d3815e943e6e68e8a8d3beb3d
2020-02-13T18:25:51.0577158Z [command]git describe --tags 6f8942e7b9a6be4d3815e943e6e68e8a8d3beb3d
2020-02-13T18:25:51.0610262Z v0.1.11
2020-02-13T18:25:51.0613530Z [command]git log v0.1.11..HEAD --pretty=format:'%s%n%b==============================================' --abbrev-commit
2020-02-13T18:25:51.0646755Z 'feat(pencil): add <graphiteWidth> option
2020-02-13T18:25:51.0696234Z =============================================='::debug::Analyzing commit: %s
2020-02-13T18:25:51.0700996Z ##[debug]The commit should not trigger a release
2020-02-13T18:25:51.0701418Z ##[debug]Analyzing commit: %s
2020-02-13T18:25:51.0701718Z ##[debug]The commit should not trigger a release
2020-02-13T18:25:51.0702056Z ##[debug]Analysis of %s commits complete: %s release
2020-02-13T18:25:51.0707178Z ::set-output name=new_version,::0.1.12
2020-02-13T18:25:51.0735848Z ##[debug]steps.buildnumber.outputs.new_version='0.1.12'
2020-02-13T18:25:51.0739016Z ::set-output name=new_tag,::v0.1.12
2020-02-13T18:25:51.0739441Z ##[debug]steps.buildnumber.outputs.new_tag='v0.1.12'
2020-02-13T18:25:51.0739629Z ##[debug]New tag: v0.1.12
2020-02-13T18:25:51.0782031Z ##[debug]Pushing new tag to the repo
2020-02-13T18:25:51.8652780Z ##[debug]Finishing: Bump version and push tag
```

I have also tried with `perf(pencil): remove graphiteWidth option` to try to trigger a release bump, also without any luck.

```
2020-02-13T18:31:12.8794877Z v0.1.8
2020-02-13T18:31:12.8795089Z v0.1.9
2020-02-13T18:31:12.8795917Z [command]git rev-list --tags --topo-order --max-count=1
2020-02-13T18:31:12.8796391Z 517e390db133f5904e2d275a1d77b287476edcef
2020-02-13T18:31:12.8797116Z [command]git describe --tags 517e390db133f5904e2d275a1d77b287476edcef
2020-02-13T18:31:12.8797576Z v0.1.12
2020-02-13T18:31:12.8798447Z [command]git log v0.1.12..HEAD --pretty=format:'%s%n%b==============================================' --abbrev-commit
2020-02-13T18:31:12.8799070Z 'perf(pencil): remove graphiteWidth option
2020-02-13T18:31:12.8800961Z =============================================='::debug::Analyzing commit: %s
2020-02-13T18:31:12.8801702Z ##[debug]The commit should not trigger a release
2020-02-13T18:31:12.8801995Z ##[debug]Analyzing commit: %s
2020-02-13T18:31:12.8802499Z ##[debug]The commit should not trigger a release
2020-02-13T18:31:12.8802855Z ##[debug]Analysis of %s commits complete: %s release
2020-02-13T18:31:12.8804217Z ::set-output name=new_version,::0.1.13
2020-02-13T18:31:12.8846706Z ##[debug]steps.buildnumber.outputs.new_version='0.1.13'
2020-02-13T18:31:12.8847862Z ::set-output name=new_tag,::v0.1.13
2020-02-13T18:31:12.8848248Z ##[debug]steps.buildnumber.outputs.new_tag='v0.1.13'
2020-02-13T18:31:12.8848928Z ##[debug]New tag: v0.1.13
2020-02-13T18:31:12.8850376Z ##[debug]Pushing new tag to the repo
2020-02-13T18:31:13.4915794Z ##[debug]Finishing: Bump version and push tag
```

**Comment by tflander** [comment]
I got a minor version bump that I didn't expect.  I don't know if I can get one that I expect. Let me take some time to investigate and I will reply.  Thank you for the support.

**Comment by tflander** [comment]
Not working for me either.  Docs for the failure here: https://github.com/tflander/python-tag-release-spike/wiki.

I would appreciate if you fork this repo and try it out, unless you see the problem fast...

**Comment by mathieudutour** [comment]
should be fixed with v3.1. For some reason, on the CI there is a `'` before every commit message

**Comment by tflander** [comment]
Thank you!  Minor bump is working as advertised.  Major bump still not working.  I'm going to fork and debug.

```
2020-02-24T15:28:06.2502928Z [command]git log v0.1.0..HEAD --pretty=format:'%s%n%b==============================================' --abbrev-commit
2020-02-24T15:28:06.2535698Z 'BREAKING CHANGE: The graphiteWidth option has been removed.
2020-02-24T15:28:06.2582599Z =============================================='Analyzing commit: BREAKING CHANGE: The graphiteWidth option has been removed.
2020-02-24T15:28:06.2588202Z The commit should not trigger a release
2020-02-24T15:28:06.2588963Z Analysis of 1 commits complete: no release
2020-02-24T15:28:06.2596152Z ::set-output name=new_version,::0.1.1
2020-02-24T15:28:06.2618552Z ##[debug]steps.tag-it.outputs.new_version='0.1.1'
2020-02-24T15:28:06.2621534Z ::set-output name=new_tag,::v0.1.1
2020-02-24T15:28:06.2621848Z ##[debug]steps.tag-it.outputs.new_tag='v0.1.1'
2020-02-24T15:28:06.2622043Z ##[debug]New tag: v0.1.1
2020-02-24T15:28:06.2661751Z ##[debug]Pushing new tag to the repo
2020-02-24T15:28:07.0416524Z ##[debug]Node Action run completed with exit code 0
2020-02-24T15:28:07.0417479Z ##[debug]Finishing: create semantic version tag
2020-02-24T15:28:07.0452294Z ##[debug]Evaluating condition for step: 'release'
2020-02-24T15:28:07.0453468Z ##[debug]Parsing expression: <success()>
2020-02-24T15:28:07.0455211Z ##[debug]Evaluating: success()
2020-02-24T15:28:07.0455474Z ##[debug]Evaluating success:
2020-02-24T15:28:07.0456107Z ##[debug]=> true
```

**Comment by mathieudutour** [comment]
The `BREAKING CHANGE` needs to be in the description of the commit, not the message (as shown in the README)

**Comment by tflander** [comment]
Perfect!  Thank you again.  That was a RTFM error (read the fine manual).

**Comment by jkworth** [comment]
I was having the same issue as others above. Found that if doing a PR and using the merge option it would not find the "BREAKING CHANGE" message in any commit. Tried by closing PR using the rebase option and it had no problems. Seems weird that i have to do a rebase for this but at least for now i know.
